export const staffData = [
  {
    id: "20200367378",
    name: "John Doe",
    position: "Software Engineer",
    email: "john.doe@example.com",
    department: "Engineering",
  },
  {
    id: "20240365428",
    name: "Jane Smith",
    position: "Product Manager",
    email: "jane.smith@example.com",
    department: "Product",
  },
  {
    id: "19930365428",
    name: "Alice Johnson",
    position: "Data Analyst",
    email: "alice.johnson@example.com",
    department: "Data Science",
  },
  {
    id: "20040363728",
    name: "Bob Brown",
    position: "HR Manager",
    email: "bob.brown@example.com",
    department: "Human Resources",
  },
  {
    id: "20240364567",
    name: "Charlie Davis",
    position: "DevOps Engineer",
    email: "charlie.davis@example.com",
    department: "Engineering",
  },
  {
    id: "20240465428",
    name: "Diana Evans",
    position: "UX Designer",
    email: "diana.evans@example.com",
    department: "Design",
  },
  {
    id: "20240363452",
    name: "Ethan Frank",
    position: "QA Engineer",
    email: "ethan.frank@example.com",
    department: "Quality Assurance",
  },
  {
    id: "20222265428",
    name: "Fiona Green",
    position: "Marketing Specialist",
    email: "fiona.green@example.com",
    department: "Marketing",
  },
  {
    id: "20249046528",
    name: "George Hill",
    position: "Sales Manager",
    email: "george.hill@example.com",
    department: "Sales",
  },
  {
    id: "19990356728",
    name: "Hannah Ives",
    position: "Financial Analyst",
    email: "hannah.ives@example.com",
    department: "Finance",
  },
];
